version: "3.8"

services: 
    django: 
        build: .
        container_name: django
        command: make runserver
        volumes: 
            - .:/usr/src/app/
        ports:
            - "8000:8000"
        env_file: 
          - .env
        depends_on: 
          - pgdb
          - redis
    celery:
        build: .
        container_name: celery
        command: celery -A core worker -l INFO
        env_file: 
          - .env
        volumes:
          - .:/user/src/app/
        depends_on:
          - django
          - redis
    pgdb:
        image: postgres
        container_name: pgdb
        env_file: 
          - .env
        volumes:
            - pgdata:/var/lib/postgresql/data/
    redis:
        image: "redis:alpine"
volumes:
    pgdata:
    