- hosts: my_servers
  gather_facts: no
  tasks:
    - name: install packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: latest
      loop:
        - redis-server
        - postgresql
        - git
      become: yes